timezone: Europe/Rome
baseurl: /ui
permalink: pretty

# COLLECTIONS
collections:
  docs:
    output: true
    title: Docs

# DEFAULTS
defaults:
  - scope:
      path: ""
    values:
      layout: default