timezone: Europe/Rome
baseurl: /ui
permalink: pretty

# COLLECTIONS
collections:
  docs:
    output: true
    title: Docs
  games:
    output: true
    title: Games

# DEFAULTS
defaults:
  - scope:
      path: ""
    values:
      layout: default